### ISSUE TITLE
Circle number is skewed

### ISSUE THREAD

**Issue by nikibrown** [IAmFrnak/foodproject#3]
https://github.com/IAmFrnak/foodproject/blob/510219b484af8eeaa99f528984f91489837bf71c/styles.scss#L604

Looks like you don't need the `width: 40px;` for .circle-number inside of your media query. 

![circle-number](https://github.com/IAmFrnak/foodproject/assets/284173/00c79f0c-96cc-4971-ae02-07a3db99f9da)

**Comment by IAmFrnak** [comment]
https://github.com/IAmFrnak/foodproject/pull/6 fixed in this pr
